version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/database.sqlite:/var/www/html/database.sqlite
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data